Fix for test LocationUsageTrackingTest.testUsageIncludesStartAndStopEvents
It is possible to create the event in the same ms as the stopwatch:
java.lang.AssertionError: date=1404984334453; pre=1404984334448; post=1404984334453 expected [true] but found [false]

Just include the start and stop times in the allowed range. Also display the time in ms so the problem is visible.